version: '3.1'

services:
    db:
        image: postgres:13-alpine
        restart: always 
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: communication
        ports:
            - "5432:5432"
            