version: '3.1'

services:
    db:
        image: postgres:13-alpine
        container_name: db
        restart: always 
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: communication
    app:
        build: .
        container_name: api
        ports:
            - 8081:8081
        depends_on:
            - db
            